#!/bin/bash
#. ./.env && AMO_CLIENT_ID=${AMO_CLIENT_ID} AMO_CLIENT_SECRET=${AMO_CLIENT_SECRET} AMO_TOKEN_PATH=${AMO_TOKEN_PATH} MONGO_HOST=${MONGO_HOST} MONGO_DB=${MONGO_DB} php -i

cd /var/www/amocrm-auto
. ./.env && AMO_CLIENT_ID=${AMO_CLIENT_ID} AMO_CLIENT_SECRET=${AMO_CLIENT_SECRET} AMO_TOKEN_PATH=${AMO_TOKEN_PATH} MONGO_HOST=${MONGO_HOST} MONGO_PORT=${MONGO_PORT} MONGO_DB=${MONGO_DB} php updateDb.php