GET http://amo-auto.humanistic.tech/api/checkExam?userId=12
Accept: application/json

###
POST http://localhost:8180/api/saveExam
Content-Type: application/json

{
  "result": {
    "answerdTickets": 20,
    "correctAnswer": 7,
    "errorAnswer": 13,
    "ticketsCount": 20,
    "userId": 1234
  },
  "tickets": [
    {
      "answers": [],
      "correct": "3",
      "hint": " Вы обязаны обеспечить беспрепятственный проезд перекрёстка «оперативнику» с включенными специальными сигналами независимо от направления его движения. Сделать это необходимо при движении в любом направлении. (Пункты 3.1, 3.2 ПДД).",
      "image": "images/all/8_12_14.jpg",
      "selectAnswerId": 2,
      "title": "При движении в каком направлении Вы должны уступить дорогу автомобилю с включенными проблесковым маячком и специальным звуковым сигналом?"
    },
    {
      "answers": [

      ],
      "correct": "1",
      "hint": " Вы будете перестраиваться. Перед перестроением следует подать сигнал правого поворота. («Дорожные знаки», «Горизонтальная разметка» 1.19, пункт 8.1 ПДД).",
      "image": "images/all/16_11_7.jpg",
      "selectAnswerId": 3,
      "title": "Обязаны ли Вы в данной ситуации подать сигнал правого поворота?"
    },
    {
      "answers": [

      ],
      "correct": "3",
      "hint": " И знак 6.15.2 «Направление движения для грузовых автомобилей», и знак 3.4 «Движение грузовых автомобилей запрещено» распространяют своё действие только на грузовые автомобили с разрешённой максимальной массой более 3,5 т. Ваш автомобиль не относится к такому классу. Можете продолжить движение в любом направлении. («Дорожные знаки»).",
      "image": "images/all/89_10_4.jpg",
      "selectAnswerId": 1,
      "title": "Вы управляете грузовым автомобилем с разрешённой максимальной массой не более 3,5 т. В каком направлении Вам разрешено дальнейшее движение?"
    },
    {
      "answers": [

      ],
      "correct": "2",
      "hint": " Запрещается эксплуатация транспортного средства, если стояночная тормозная система не обеспечивает неподвижное состояние транспортных средств с полной нагрузкой на уклоне до 16 процентов включительно. («Перечень неисправностей» пункт 1.5.)",
      "image": "images/all/no_image.jpg",
      "selectAnswerId": 3,
      "title": "При какой неисправности тормозной системы запрещается эксплуатация транспортного средства?"
    },
    {
      "answers": [

      ],
      "correct": "3",
      "hint": " На пути движения многопутная железная дорога. Вам необходимо остановиться перед знаком 2.5 «Движение без остановки запрещено», дождаться проезда поезда и, убедившись в отсутствии приближающихся поездов с обоих направлений, продолжить дальнейшее движение. («Дорожные знаки», пункты 15.1,15.2, 15.3,15.4 ПДД).",
      "image": "images/all/8_25_16.jpg",
      "selectAnswerId": 1,
      "title": "Как Вам следует поступить в данной ситуации?"
    },
    {
      "answers": [

      ],
      "correct": "4",
      "hint": " Учебная езда на дорогах допускается только с обучающим и при наличии первоначальных навыков управления у обучаемого. Обучаемый обязан знать и выполнять требования Правил. Обучаемому на автомобиле или мотоцикле должно быть не менее 16 лет. Правильный ответ – все перечисленные требования. (Пункты 21.2, 21.4 ПДД).",
      "image": "images/all/no_image.jpg",
      "selectAnswerId": 4,
      "title": "Какие из перечисленных требований предъявляются к обучаемому на автомобиле, допущенному к учебной езде на дорогах?"
    },
    {
      "answers": [

      ],
      "correct": "2",
      "hint": " Автомобилям оперативной службы, едущим с включенным проблесковым маячком синего цвета и специальным звуковым сигналом, следует уступать дорогу, обеспечив беспрепятственный проезд. Водителю легкового автомобиля следует перестроиться на правую полосу и продолжить движение. (Пункт 3.2 ПДД).",
      "image": "images/all/6_36_6.jpg",
      "selectAnswerId": 1,
      "title": "Как следует поступить водителю легкового автомобиля при приближении автомобиля оперативной службы?"
    },
    {
      "answers": [

      ],
      "correct": "2",
      "hint": " Разметка 1.20 предупреждает о приближении к разметке 1.13, которая указывает место, где водитель должен при необходимости остановиться, уступая дорогу транспортным средствам, движущимся по пересекаемой дороге. («Горизонтальная разметка»).",
      "image": "images/all/7_6_5.jpg",
      "selectAnswerId": 2,
      "title": "Разметка в виде треугольника на полосе движения:"
    },
    {
      "answers": [

      ],
      "correct": "3",
      "hint": " Для исключения непреднамеренного скатывания автомобиля выверните колёса так, чтобы возник упор в бордюрный камень тротуара. Это препятствует дальнейшему передвижению автомобиля («А» и «В»). И, наоборот, при отсутствии упора может произойти самопроизвольное скатывание автомобиля на проезжую часть («Б» и «Г»). Эта мера является дополнительной к обязательным мерам, т.е. использованию стояночного тормоза и включению желательно более низкой передачи или заднего хода. (Пункт 12.8 ПДД. «Комментарий ПДД РФ», издательство «За рулём»).",
      "image": "images/all/11_11_19.jpg",
      "selectAnswerId": 2,
      "title": "В случае остановки на подъеме (спуске) при наличии тротуара можно предотвратить самопроизвольное скатывание автомобиля, повернув его передние колеса в положение:"
    },
    {
      "answers": [

      ],
      "correct": "4",
      "hint": " Перекрёсток неравнозначный. Главная дорога меняет направление. Транспортные средства, находящиеся на главной дороге, имеют преимущество, между собой руководствуются «правилом правой руки». После их проезда, руководствуясь этим же правилом, проедут транспортные средства, находящиеся на второстепенной дороге. Вы проезжаете первым, никому не уступая. Мотоциклист – вторым, автобус – третьим, легковой автомобиль – последним. (Пункты 13.9, 13.1, 13.11 ПДД).",
      "image": "images/all/111_30_15.jpg",
      "selectAnswerId": 4,
      "title": "Вы намерены повернуть налево. Кому Вы обязаны уступить дорогу?"
    },
    {
      "answers": [

      ],
      "correct": "1",
      "hint": " Перекрёсток равнозначный. Водители руководствуются «правилом правой руки». У Вас помеха справа будет только при движении прямо - Вы уступаете дорогу грузовому автомобилю. При повороте направо помеха справа отсутствует. (Пункт 13.11 ПДД).",
      "image": "images/all/70_28_14.jpg",
      "selectAnswerId": 3,
      "title": "Вы должны уступить дорогу грузовому автомобилю:"
    },
    {
      "answers": [

      ],
      "correct": "3",
      "hint": " При повороте направо или налево водитель обязан уступить дорогу пешеходам, переходящим проезжую часть дороги, на которую он поворачивает, и велосипедистам, независимо от того, регулируемый или нерегулируемый это перекресток. (Пункт 13.1 ПДД).",
      "image": "images/all/3_1_13.jpg",
      "selectAnswerId": 2,
      "title": "При повороте направо Вы должны уступить дорогу:"
    },
    {
      "answers": [

      ],
      "correct": "2",
      "hint": " Перекрёсток равнозначный. Трамвай на равнозначных перекрёстках имеет преимущество перед безрельсовыми транспортными средствами независимо от его дальнейшего направления движения. Безрельсовые транспортные средства руководствуются между собой «правилом правой руки», т.е. у кого помеха справа, тот и уступает дорогу. У Вас помеха справа – уступаете дорогу грузовику. (Пункт 13.11 ПДД).",
      "image": "images/all/73_31_14.jpg",
      "selectAnswerId": 2,
      "title": "Вы намерены проехать перекрёсток в прямом направлении. Ваши действия?"
    },
    {
      "answers": [

      ],
      "correct": "1",
      "hint": " Знак 3.29 «Стоянка запрещена по нечётным числам месяца» ограничивает только стоянку. Остановка в его зоне действия не запрещается в любой период времени. («Дорожные знаки»).",
      "image": "images/all/2_2_3.jpg",
      "selectAnswerId": 3,
      "title": "Разрешено ли Вам произвести остановку для посадки пассажира?"
    },
    {
      "answers": [

      ],
      "correct": "4",
      "hint": " Неисправности, указанные в ответах 1, 2, 3, перечислены в «Перечне неисправностей». Неработающий стеклоподъемник в данном перечне не указан. Следовательно, это не может быть причиной запрещения эксплуатации транспортного средства. («Перечень неисправностей» п.7.4.).",
      "image": "images/all/no_image.jpg",
      "selectAnswerId": 4,
      "title": "При какой неисправности разрешается эксплуатация транспортного средства?"
    },
    {
      "answers": [

      ],
      "correct": "3",
      "hint": " При выключенных сигналах реверсивного светофора, который расположен над полосой, обозначенной с обеих сторон разм. 1.9, въезд на эту полосу запрещен. (Пункт 6.7 ПДД).",
      "image": "images/all/3_2_5.jpg",
      "selectAnswerId": 2,
      "title": "Разрешен ли Вам выезд на полосу с реверсивным движением, если реверсивный светофор выключен?"
    },
    {
      "answers": [

      ],
      "correct": "2",
      "hint": " Из указанных знаков, действие не распространяются на транспортные средства, управляемые инвалидами I и II групп, переводящие таких инвалидов или детей-инвалидов, если на ТС установлен опознавательный знак «Инвалид»: знак «Б» – 3.2 «Движение запрещено» и знак «Г» - 3.28 «Стоянка запрещена» Правильный ответ - второй. («Дорожные знаки»).",
      "image": "images/all/77_38_3.jpg",
      "selectAnswerId": 2,
      "title": "Действие каких из указанных знаков не распространяется на транспортные средства, управляемые инвалидами I и II групп, перевозящие таких инвалидов или детей-инвалидов, если на транспортных средствах установлен опознавательный знак «Инвалид»?"
    },
    {
      "answers": [

      ],
      "correct": "2",
      "hint": " Знак 5.13.2 «Выезд на дорогу с полосой для маршрутных транспортных средств» запрещает поворот направо. Поэтому Вы можете продолжить движение прямо, налево или развернуться для движения в обратном направлении. («Дорожные знаки»).",
      "image": "images/all/51_12_3.jpg",
      "selectAnswerId": 3,
      "title": "В каких направлениях Вам можно продолжить движение на перекрёстке?"
    },
    {
      "answers": [

      ],
      "correct": "3",
      "hint": " Перекрёсток неравнозначный. Главная дорога меняет направление. Транспортные средства, находящиеся на главной дороге, имеют преимущество; между собой безрельсовые транспортные средства руководствуются «правилом правой руки», уступая трамваю, имеющему преимущество в равнозначных условиях. Трамвай «А» проезжает первым, Вы после него. Легковой автомобиль и трамвай «Б» одновременно, так как их траектории не пересекаются. («Дорожные знаки», пункты 13.9, 13.10, 13.11 ПДД).",
      "image": "images/all/129_3_15.jpg",
      "selectAnswerId": 3,
      "title": "Кому Вы обязаны уступить дорогу при повороте налево?"
    },
    {
      "answers": [

      ],
      "correct": "2",
      "hint": " Перекрёсток нерегулируемый, неравнозначный. Преимущество имеют транспортные средства, находящиеся на главной дороге, которые между собой руководствуются «правилом правой руки». После проезжают перекрёсток транспортные средства, находящиеся на второстепенной дороге. Первым проезжает грузовик, Вы ему уступаете. Последним проедет легковой автомобиль. (Пункты 13.3, 13.9, 13.12 ПДД).",
      "image": "images/all/117_36_15.jpg",
      "selectAnswerId": 3,
      "title": "Как Вам следует поступить при повороте налево?"
    }
  ]
}

###

